android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API_LEVEL
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
  - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
before_deploy:
- cp $TRAVIS_BUILD_DIR/.my_key_store $HOME
- cd app/build/outputs/apk/
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/my_key_store.jks
- storepass $storepass -keypass $keypass app-release-unsigned.apk romakononovich
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/29.0.3/zipalign -v 4 app-release-unsigned.apk AppWeather.apk"
before_install:
- openssl aes-256-cbc -K $encrypted_64124e1c0c0f_key -iv $encrypted_64124e1c0c0f_iv
  -in my_key_store.jks.enc -out my_key_store.jks -d
- openssl aes-256-cbc -K $encrypted_bf364cab31c0_key -iv $encrypted_bf364cab31c0_iv
- in test.jks.enc -out test.jks -d
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
- "./gradlew dependencies || true"
before_script:
- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a -c
  32M
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- sleep 180
- adb devices
- adb shell input keyevent 82 &
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  file: AppWeather.apk
  provider: releases
  skip_cleanup: true
  on:
    jdk: oraclejdk8
    repo: AleksKirienko/shift_stream
    tags: true
dist: trusty
env:
  global:
  - ANDROID_API=29
  - EMULATOR_API_LEVEL=29
  - ANDROID_BUILD_TOOLS=29.0.3
  - ADB_INSTALL_TIMEOUT=5
  - secure: a+jI9r33Q5V1DYbI5Ik3gSN29NSfeCvbdPgyxgGX3m0hpizj6pXDR2fCfIelsf6N3O0sMMDhMScWvQXAJpIstTp5QV2HlMon80ecabdPLs44H8SaYp+dPISoM2aPRrrQ2ZaUZ1lu0Xx+HmMH8+xqFDOmfiPcCWymqPn30lSyvHJv03Gdy6TDwATiI1u2uTEfcN9nh+5YozLysC0skDoAwy3XmlEsNKPNiEY4HwcHZnoAcdliSzlOmgHYrKpeeFWvdv0t0zJtu6YlnS2NptVy+q5YzWpwK6aq5Tgvb976HXnA4VYAyJ1+jYeRGTL8mrg/XXtFxWiuLxRJ4wZ7Y9NNm90hWW7ThO3aT3XLekL7Cohwy6Im6dIofdwHgYgxWckJGH0hTX8v1AZMPrg5//aqjTdbVeHHzbpb5Q8hFZ6LhWVqDv79MtafSqYrpxCRudXHUA/EGLtLa1GkCo3pEb0bvQ5eZUTzuoMCcPkcXeGkXq6mYnHaPXUNxmXugStLo4f25k1HoWxmgG9NW9ocxZyvcsNd98bAsVgsglODKXwR9i5I3LR5E1DhPPvnNm0sqfrFxVv/CwBvZ7NeVHjVzF/ClxbIs9MSpvMzoUgxEmo7NUc9cZVWS+cJnluXu811LcMYib+a04V0HDZYqsFfbdif2BJNKeWepDES0IKnPgD3VTo=
  - secure: eESoUZ+Gi/E65NImVvz9KVeHKeBIaXbpxnWU16JoGavCBsvsCUFXElkdaD8JSJIHRoq704Xtsy+KhKgRWKXpcmx3va9cDoqLeOqiZVtsuaxc16VZw1xM0XNtPE0tYmFu0+8yl0bnSFlsvMA7MWZ6jlwqCeaoIH7UUwgckhAUZzNOt7fep60Vl1SWxocYOwVHZxx2EqDdlKSK4mlC6aiOMDnuEYMh00rUpkvwzB6ysbWS2tV9ukLlyxNN2AmJoC1a8YfA3BT4dQin/JVT0+8dvvDznyeeysl/jVa7oA3bIR9yTkkrDB3rWXOwUcvSvgVS7nBQ4MKMZKAIHzSsS+JZ6HVewJihFmwlu6vx86Sf1utZbKQd11M+2ippHwrm+aK58AS5uodHgW5HnHmEiT38aC+lZEfdlRHg6Lk3SEhWHhB8O9NzBe+WPLrSaTjIbjahER8qCwmwTqV0DD6zee2vFDg2Pjf7ZF/YE4QiWi8bhmK4x/pbt04Iy8h1nXK70Vo9CYi963Lvk2WloL3UeOrWQQnrXJOVhliMtV8YjuKNJKuduzn3oDNUXTXAU3fh+VtOoBM5Ox+Iut9u+YgAtXT5BrQ/VQMBKO5TIuZtdlieu6KGiFcFfzch2PfqRa/EvW+4QDuNyTBMA8l550DhulrjaD22KhbRSMcy1OJoBLr75uo=
jdk: oraclejdk8
language: android
script:
- "./gradlew clean build connectedCheck -PdisablePreDex"
sudo: required
 
